# Generated by Django 5.2.1 on 2025-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('industry', models.CharField(blank=True, choices=[('manufacturing', 'Manufacturing'), ('Steel_and_metal', 'Steel and Metal'), ('cement', 'Cement'), ('textile', 'Textile'), ('chemical', 'Chemical'), ('food_processing', 'Food Processsing'), ('other', 'Other')], max_length=50)),
                ('energy_needs', models.CharField(blank=True, choices=[('<50', 'Less than 50 tons'), ('50-200', '50–200 tons'), ('200-500', '200–500 tons'), ('500+', '500+ tons')], max_length=20)),
                ('project_details', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
